### ISSUE TITLE
[Bug]: Sensor crashes with "'list' object has no attribute 'get'" on 1.8.1

### ISSUE THREAD

**Issue by RikyUnreal** [FaserF/ha-whatsapp#83]
### Integration Version

1.8.1

### Home Assistant Version

2026.7.2

### WhatsApp Addon Version (if used)

1.8.1

### Setup Type

Hassio Addon (FaserF/hassio-addons)

### Describe the bug

After updating to 1.8.1, one of the integration's sensors throws a continuous error in the HA log. It started exactly when I updated to 1.8.1 and repeats constantly (11,000+ times in ~4 days).

Sending and receiving messages both still work correctly (whatsapp_message_received events fire and whatsapp.send_message works), so this only seems to affect a sensor's state calculation, but it floods the log and causes constant SD-card writes.

The error is in sensor.py at native_value (line 227). It looks like the code expects a dict but receives a list, possibly related to a change in the "Chats"/groups data format in 1.8.1.

### Steps to Reproduce

1. Update add-on and integration to 1.8.1
2. Restart Home Assistant
3. Check the Home Assistant log
4. The sensor error appears continuously

### Expected Behavior

The sensor should calculate its state without crashing, as it did before updating to 1.8.1.

### Diagnostic Information

```yaml

```

### Relevant log output

```shell
Logger: custom_components.whatsapp.coordinator
Source: helpers/update_coordinator.py:202

Unexpected error updating listener for whatsapp

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 202, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 604, in state
    value = self.native_value
  File "/config/custom_components/whatsapp/sensor.py", line 227, in native_value
    return 0
AttributeError: 'list' object has no attribute 'get'
```

**Comment by FaserF** [comment]
Thank you for reporting, fixed with release 1.8.2
